CREATE TABLE users(
  id INT AUTO_INCREMENT PRIMARY KEY,
  nickName VARCHAR(50) NOT NULL,
  avatarUrl VARCHAR(100) NOT NULL
);

CREATE TABLE class(
  id INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(50) NOT NULL,
  address VARCHAR(100) NOT NULL,
  `time` INT NOT NULL,
  teacher VARCHAR(10) NOT NULL,
  credits INT NOT NULL DEFAULT 0
);

CREATE TABLE select_class(
  id INT AUTO_INCREMENT PRIMARY KEY,
  users_id INT NOT NULL,
  class_id INT NOT NULL,
  FOREIGN KEY (users_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (class_id) REFERENCES class(id) ON DELETE CASCADE
);